# Generated by Django 3.2.4 on 2021-06-30 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=datetime.datetime(2021, 6, 30, 9, 16, 0, 841359, tzinfo=utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
